### ISSUE TITLE
Posistemė Nr. 4. Viešinamos informacijos posistemė

### ISSUE THREAD

**Issue by RMasiliunaite** [Viesuju-pirkimu-tarnyba/saule#18]
# 3.3.4	SAULĖ IS informacijos viešinimas

Posistemė skirta SAULĖ IS duomenų viešinimo procesų tvarkymui, prenumeratų procesų valdymui ir apklausų sudarymui, atlikimui ir automatiniam rezultatų apskaičiavimui. Posistemė užtikrina automatinį duomenų viešinimą išoriniame portale, socialiniuose tinkluose, informacijos perdavimą kitoms IS ir kitiems informacijos viešinimo priemonėms įvairiais nustatytais duomenų pateikimo formatais (įskaitant, bet neapsiribojant, API (XML). Šios posistemės aprašyme pateikiami šie procesai:
•	SAULĖ IS duomenų viešinimas;
•	SAULĖ IS prenumeratų valdymas;
•	Apklausų sudarymas ir valdymas.

- [ ] [3.3.4.1	SAULĖ IS informacijos viešinimas](https://github.com/Viesuju-pirkimu-tarnyba/saule/issues/31)

- [ ] [3.3.4.2	SAULĖ IS prenumeratų valdymas](https://github.com/Viesuju-pirkimu-tarnyba/saule/issues/32)
- [ ] [3.3.4.3	Apklausų sudarymas ir valdymas](https://github.com/Viesuju-pirkimu-tarnyba/saule/issues/33)
